// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addRandomEventQuestionsAll = `-- name: AddRandomEventQuestionsAll :exec
INSERT INTO event_questions (event_id, question_id)
SELECT $1, q.id
FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE c.deleted_at IS NULL
  AND q.id NOT IN (SELECT question_id FROM event_questions WHERE event_id = $1)
ORDER BY RANDOM()
LIMIT $2
`

type AddRandomEventQuestionsAllParams struct {
	EventID uuid.UUID `json:"event_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) AddRandomEventQuestionsAll(ctx context.Context, arg AddRandomEventQuestionsAllParams) error {
	_, err := q.db.ExecContext(ctx, addRandomEventQuestionsAll, arg.EventID, arg.Limit)
	return err
}

const addRandomEventQuestionsByCategory = `-- name: AddRandomEventQuestionsByCategory :exec
INSERT INTO event_questions (event_id, question_id)
SELECT $1, q.id
FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE q.category_id = $2 AND c.deleted_at IS NULL
  AND q.id NOT IN (SELECT question_id FROM event_questions WHERE event_id = $1)
ORDER BY RANDOM()
LIMIT $3
`

type AddRandomEventQuestionsByCategoryParams struct {
	EventID    uuid.UUID     `json:"event_id"`
	CategoryID sql.NullInt32 `json:"category_id"`
	Limit      int32         `json:"limit"`
}

func (q *Queries) AddRandomEventQuestionsByCategory(ctx context.Context, arg AddRandomEventQuestionsByCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addRandomEventQuestionsByCategory, arg.EventID, arg.CategoryID, arg.Limit)
	return err
}

const approveUserEvent = `-- name: ApproveUserEvent :one
UPDATE user_event_approvals
SET status = 'approved'
WHERE id = $1
RETURNING id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at
`

func (q *Queries) ApproveUserEvent(ctx context.Context, id uuid.UUID) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, approveUserEvent, id)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const blockSession = `-- name: BlockSession :exec
UPDATE sessions
SET is_blocked = true
WHERE id = $1
`

func (q *Queries) BlockSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, blockSession, id)
	return err
}

const calculateScore = `-- name: CalculateScore :one
SELECT COALESCE(SUM(q.weight), 0)::numeric as total_score
FROM user_answers ua
JOIN questions q ON ua.question_id = q.id
WHERE ua.approval_id = $1 AND ua.is_correct = true
`

func (q *Queries) CalculateScore(ctx context.Context, approvalID uuid.NullUUID) (string, error) {
	row := q.db.QueryRowContext(ctx, calculateScore, approvalID)
	var total_score string
	err := row.Scan(&total_score)
	return total_score, err
}

const checkDuplicateQuestion = `-- name: CheckDuplicateQuestion :one
SELECT q.id, q.category_id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.weight, q.created_at FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE c.deleted_at IS NULL
  AND REGEXP_REPLACE(q.question_text, '^[[:space:][:digit:].)*#_-]+', '') ILIKE REGEXP_REPLACE($1::text, '^[[:space:][:digit:].)*#_-]+', '')
  AND ($2::uuid IS NULL OR q.id <> $2::uuid)
LIMIT 1
`

type CheckDuplicateQuestionParams struct {
	QuestionText string        `json:"question_text"`
	ExcludeID    uuid.NullUUID `json:"exclude_id"`
}

func (q *Queries) CheckDuplicateQuestion(ctx context.Context, arg CheckDuplicateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, checkDuplicateQuestion, arg.QuestionText, arg.ExcludeID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const countAvailableQuestionsForEventAll = `-- name: CountAvailableQuestionsForEventAll :one
SELECT COUNT(*) FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE c.deleted_at IS NULL
  AND q.id NOT IN (SELECT question_id FROM event_questions WHERE event_id = $1)
`

func (q *Queries) CountAvailableQuestionsForEventAll(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableQuestionsForEventAll, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAvailableQuestionsForEventByCategory = `-- name: CountAvailableQuestionsForEventByCategory :one
SELECT COUNT(*) FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE q.category_id = $2 AND c.deleted_at IS NULL
  AND q.id NOT IN (SELECT question_id FROM event_questions WHERE event_id = $1)
`

type CountAvailableQuestionsForEventByCategoryParams struct {
	EventID    uuid.UUID     `json:"event_id"`
	CategoryID sql.NullInt32 `json:"category_id"`
}

func (q *Queries) CountAvailableQuestionsForEventByCategory(ctx context.Context, arg CountAvailableQuestionsForEventByCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableQuestionsForEventByCategory, arg.EventID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories
WHERE deleted_at IS NULL AND ($1::text = '' OR name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountCategories(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventParticipants = `-- name: CountEventParticipants :one
SELECT COUNT(*) FROM user_event_approvals
WHERE event_id = $1
`

func (q *Queries) CountEventParticipants(ctx context.Context, eventID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventParticipants, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventQuestions = `-- name: CountEventQuestions :one
SELECT COUNT(*) FROM event_questions
WHERE event_id = $1
`

func (q *Queries) CountEventQuestions(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventQuestions, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
WHERE $1::text = '' OR to_tsvector('indonesian', name) @@ plainto_tsquery('indonesian', $1::text)
`

func (q *Queries) CountEvents(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestions = `-- name: CountQuestions :one
SELECT COUNT(*) FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE c.deleted_at IS NULL
  AND ($1::int IS NULL OR q.category_id = $1::int)
  AND ($2::text = '' OR to_tsvector('indonesian', q.question_text) @@ plainto_tsquery('indonesian', $2::text))
`

type CountQuestionsParams struct {
	CategoryID sql.NullInt32 `json:"category_id"`
	Search     string        `json:"search"`
}

func (q *Queries) CountQuestions(ctx context.Context, arg CountQuestionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuestions, arg.CategoryID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestionsByCategory = `-- name: CountQuestionsByCategory :one
SELECT COUNT(*) FROM questions
WHERE category_id = $1
`

func (q *Queries) CountQuestionsByCategory(ctx context.Context, categoryID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuestionsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUpcomingEvents = `-- name: CountUpcomingEvents :one
SELECT COUNT(*) FROM events
WHERE end_time > NOW()
`

func (q *Queries) CountUpcomingEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUpcomingEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserApprovals = `-- name: CountUserApprovals :one
SELECT COUNT(*) FROM user_event_approvals
WHERE user_id = $1
`

func (q *Queries) CountUserApprovals(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserApprovals, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
  AND ($1::text = '' OR full_name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name)
VALUES ($1)
RETURNING id, name, deleted_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.DeletedAt)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, start_time, end_time, duration_minutes, passing_grade)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, start_time, end_time, duration_minutes, passing_grade, created_at
`

type CreateEventParams struct {
	Name            string    `json:"name"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	PassingGrade    string    `json:"passing_grade"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.PassingGrade,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
	)
	return i, err
}

const createEventQuestion = `-- name: CreateEventQuestion :exec
INSERT INTO event_questions (event_id, question_id)
VALUES ($1, $2)
`

type CreateEventQuestionParams struct {
	EventID    uuid.UUID `json:"event_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) CreateEventQuestion(ctx context.Context, arg CreateEventQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createEventQuestion, arg.EventID, arg.QuestionID)
	return err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at
`

type CreateQuestionParams struct {
	CategoryID    sql.NullInt32 `json:"category_id"`
	QuestionText  string        `json:"question_text"`
	OptionA       string        `json:"option_a"`
	OptionB       string        `json:"option_b"`
	OptionC       string        `json:"option_c"`
	OptionD       string        `json:"option_d"`
	CorrectAnswer string        `json:"correct_answer"`
	Weight        int32         `json:"weight"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.CategoryID,
		arg.QuestionText,
		arg.OptionA,
		arg.OptionB,
		arg.OptionC,
		arg.OptionD,
		arg.CorrectAnswer,
		arg.Weight,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, refresh_token, is_blocked, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, full_name, role, photo_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	FullName     string         `json:"full_name"`
	Role         string         `json:"role"`
	PhotoUrl     sql.NullString `json:"photo_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.PhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteEventQuestion = `-- name: DeleteEventQuestion :exec
DELETE FROM event_questions
WHERE event_id = $1 AND question_id = $2
`

type DeleteEventQuestionParams struct {
	EventID    uuid.UUID `json:"event_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) DeleteEventQuestion(ctx context.Context, arg DeleteEventQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventQuestion, arg.EventID, arg.QuestionID)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const enrollUserToEvent = `-- name: EnrollUserToEvent :one
INSERT INTO user_event_approvals (user_id, event_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at
`

type EnrollUserToEventParams struct {
	UserID  uuid.NullUUID `json:"user_id"`
	EventID uuid.NullUUID `json:"event_id"`
}

func (q *Queries) EnrollUserToEvent(ctx context.Context, arg EnrollUserToEventParams) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, enrollUserToEvent, arg.UserID, arg.EventID)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const finishExam = `-- name: FinishExam :exec
UPDATE user_event_approvals
SET is_completed = true, completed_at = NOW(), score = $2, is_passed = $3
WHERE id = $1
`

type FinishExamParams struct {
	ID       uuid.UUID      `json:"id"`
	Score    sql.NullString `json:"score"`
	IsPassed sql.NullBool   `json:"is_passed"`
}

func (q *Queries) FinishExam(ctx context.Context, arg FinishExamParams) error {
	_, err := q.db.ExecContext(ctx, finishExam, arg.ID, arg.Score, arg.IsPassed)
	return err
}

const getAllEventParticipantsForExport = `-- name: GetAllEventParticipantsForExport :many
SELECT u.username, u.full_name, uea.status, uea.is_completed, uea.score, uea.is_passed, uea.started_at, uea.completed_at
FROM users u
JOIN user_event_approvals uea ON u.id = uea.user_id
WHERE uea.event_id = $1
ORDER BY u.full_name ASC
`

type GetAllEventParticipantsForExportRow struct {
	Username    string         `json:"username"`
	FullName    string         `json:"full_name"`
	Status      string         `json:"status"`
	IsCompleted bool           `json:"is_completed"`
	Score       sql.NullString `json:"score"`
	IsPassed    sql.NullBool   `json:"is_passed"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) GetAllEventParticipantsForExport(ctx context.Context, eventID uuid.NullUUID) ([]GetAllEventParticipantsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEventParticipantsForExport, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllEventParticipantsForExportRow{}
	for rows.Next() {
		var i GetAllEventParticipantsForExportRow
		if err := rows.Scan(
			&i.Username,
			&i.FullName,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.IsPassed,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApprovalById = `-- name: GetApprovalById :one
SELECT id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at FROM user_event_approvals WHERE id = $1
`

func (q *Queries) GetApprovalById(ctx context.Context, id uuid.UUID) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalById, id)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getApprovalStatus = `-- name: GetApprovalStatus :one
SELECT id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at FROM user_event_approvals
WHERE user_id = $1 AND event_id = $2 LIMIT 1
`

type GetApprovalStatusParams struct {
	UserID  uuid.NullUUID `json:"user_id"`
	EventID uuid.NullUUID `json:"event_id"`
}

func (q *Queries) GetApprovalStatus(ctx context.Context, arg GetApprovalStatusParams) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalStatus, arg.UserID, arg.EventID)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT id, name, deleted_at FROM categories
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCategoryById(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryById, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.DeletedAt)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, deleted_at FROM categories
WHERE name ILIKE $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.DeletedAt)
	return i, err
}

const getEventById = `-- name: GetEventById :one
SELECT id, name, start_time, end_time, duration_minutes, passing_grade, created_at FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
	)
	return i, err
}

const getEventTotalWeight = `-- name: GetEventTotalWeight :one
SELECT COALESCE(SUM(q.weight), 0)::numeric as total_weight
FROM event_questions eq
JOIN questions q ON eq.question_id = q.id
WHERE eq.event_id = $1
`

func (q *Queries) GetEventTotalWeight(ctx context.Context, eventID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getEventTotalWeight, eventID)
	var total_weight string
	err := row.Scan(&total_weight)
	return total_weight, err
}

const getQuestionById = `-- name: GetQuestionById :one
SELECT id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at FROM questions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQuestionById(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionById, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token, is_blocked, expires_at, created_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAnswersDetail = `-- name: GetUserAnswersDetail :many
SELECT
    ua.id as answer_id,
    ua.selected_answer,
    ua.is_correct,
    q.id as question_id,
    q.question_text,
    q.option_a,
    q.option_b,
    q.option_c,
    q.option_d,
    q.correct_answer,
    q.weight
FROM user_answers ua
JOIN questions q ON ua.question_id = q.id
WHERE ua.approval_id = $1
`

type GetUserAnswersDetailRow struct {
	AnswerID       uuid.UUID      `json:"answer_id"`
	SelectedAnswer sql.NullString `json:"selected_answer"`
	IsCorrect      sql.NullBool   `json:"is_correct"`
	QuestionID     uuid.UUID      `json:"question_id"`
	QuestionText   string         `json:"question_text"`
	OptionA        string         `json:"option_a"`
	OptionB        string         `json:"option_b"`
	OptionC        string         `json:"option_c"`
	OptionD        string         `json:"option_d"`
	CorrectAnswer  string         `json:"correct_answer"`
	Weight         int32          `json:"weight"`
}

func (q *Queries) GetUserAnswersDetail(ctx context.Context, approvalID uuid.NullUUID) ([]GetUserAnswersDetailRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAnswersDetail, approvalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAnswersDetailRow{}
	for rows.Next() {
		var i GetUserAnswersDetailRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.SelectedAnswer,
			&i.IsCorrect,
			&i.QuestionID,
			&i.QuestionText,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.CorrectAnswer,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at FROM users
WHERE username = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, deleted_at FROM categories
WHERE deleted_at IS NULL AND ($3::text = '' OR name ILIKE '%' || $3::text || '%')
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventParticipants = `-- name: ListEventParticipants :many
SELECT u.id, u.username, u.full_name, uea.status, uea.is_completed, uea.score, uea.is_passed
FROM users u
JOIN user_event_approvals uea ON u.id = uea.user_id
WHERE uea.event_id = $1
ORDER BY u.full_name ASC
LIMIT $2 OFFSET $3
`

type ListEventParticipantsParams struct {
	EventID uuid.NullUUID `json:"event_id"`
	Limit   int32         `json:"limit"`
	Offset  int32         `json:"offset"`
}

type ListEventParticipantsRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	FullName    string         `json:"full_name"`
	Status      string         `json:"status"`
	IsCompleted bool           `json:"is_completed"`
	Score       sql.NullString `json:"score"`
	IsPassed    sql.NullBool   `json:"is_passed"`
}

func (q *Queries) ListEventParticipants(ctx context.Context, arg ListEventParticipantsParams) ([]ListEventParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventParticipants, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventParticipantsRow{}
	for rows.Next() {
		var i ListEventParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.IsPassed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventQuestions = `-- name: ListEventQuestions :many
SELECT q.id, q.category_id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.weight, q.created_at FROM questions q
JOIN event_questions eq ON q.id = eq.question_id
WHERE eq.event_id = $1
ORDER BY q.created_at ASC
LIMIT $2 OFFSET $3
`

type ListEventQuestionsParams struct {
	EventID uuid.UUID `json:"event_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListEventQuestions(ctx context.Context, arg ListEventQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listEventQuestions, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.QuestionText,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.CorrectAnswer,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, start_time, end_time, duration_minutes, passing_grade, created_at FROM events
WHERE $3::text = '' OR to_tsvector('indonesian', name) @@ plainto_tsquery('indonesian', $3::text)
ORDER BY name ASC, start_time ASC, end_time ASC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.PassingGrade,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT q.id, q.category_id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.weight, q.created_at FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE c.deleted_at IS NULL
  AND ($3::int IS NULL OR q.category_id = $3::int)
  AND ($4::text = '' OR to_tsvector('indonesian', q.question_text) @@ plainto_tsquery('indonesian', $4::text))
ORDER BY q.category_id ASC, q.question_text ASC
LIMIT $1 OFFSET $2
`

type ListQuestionsParams struct {
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
	CategoryID sql.NullInt32 `json:"category_id"`
	Search     string        `json:"search"`
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.QuestionText,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.CorrectAnswer,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT id, name, start_time, end_time, duration_minutes, passing_grade, created_at FROM events
WHERE end_time > NOW()
ORDER BY start_time ASC
LIMIT $1 OFFSET $2
`

type ListUpcomingEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.PassingGrade,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserApprovals = `-- name: ListUserApprovals :many
SELECT e.id, e.name, e.start_time, e.end_time, e.duration_minutes, e.passing_grade, 
       uea.id as approval_id, uea.status, uea.is_completed, uea.score, uea.is_passed, uea.started_at, uea.completed_at
FROM events e
JOIN user_event_approvals uea ON e.id = uea.event_id
WHERE uea.user_id = $1
ORDER BY e.start_time DESC
LIMIT $2 OFFSET $3
`

type ListUserApprovalsParams struct {
	UserID uuid.NullUUID `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListUserApprovalsRow struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	DurationMinutes int32          `json:"duration_minutes"`
	PassingGrade    string         `json:"passing_grade"`
	ApprovalID      uuid.UUID      `json:"approval_id"`
	Status          string         `json:"status"`
	IsCompleted     bool           `json:"is_completed"`
	Score           sql.NullString `json:"score"`
	IsPassed        sql.NullBool   `json:"is_passed"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
}

func (q *Queries) ListUserApprovals(ctx context.Context, arg ListUserApprovalsParams) ([]ListUserApprovalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserApprovals, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserApprovalsRow{}
	for rows.Next() {
		var i ListUserApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.PassingGrade,
			&i.ApprovalID,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.IsPassed,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
  AND ($3::text = '' OR full_name ILIKE '%' || $3::text || '%')
ORDER BY full_name ASC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserEvent = `-- name: RevokeUserEvent :one
UPDATE user_event_approvals
SET status = 'revoked'
WHERE id = $1
RETURNING id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at
`

func (q *Queries) RevokeUserEvent(ctx context.Context, id uuid.UUID) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, revokeUserEvent, id)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const saveUserAnswer = `-- name: SaveUserAnswer :one
INSERT INTO user_answers (approval_id, question_id, selected_answer, is_correct)
VALUES ($1, $2, $3, $4)
ON CONFLICT (approval_id, question_id) 
DO UPDATE SET 
    selected_answer = EXCLUDED.selected_answer, 
    is_correct = EXCLUDED.is_correct
RETURNING id, approval_id, question_id, selected_answer, is_correct, created_at
`

type SaveUserAnswerParams struct {
	ApprovalID     uuid.NullUUID  `json:"approval_id"`
	QuestionID     uuid.NullUUID  `json:"question_id"`
	SelectedAnswer sql.NullString `json:"selected_answer"`
	IsCorrect      sql.NullBool   `json:"is_correct"`
}

func (q *Queries) SaveUserAnswer(ctx context.Context, arg SaveUserAnswerParams) (UserAnswer, error) {
	row := q.db.QueryRowContext(ctx, saveUserAnswer,
		arg.ApprovalID,
		arg.QuestionID,
		arg.SelectedAnswer,
		arg.IsCorrect,
	)
	var i UserAnswer
	err := row.Scan(
		&i.ID,
		&i.ApprovalID,
		&i.QuestionID,
		&i.SelectedAnswer,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const setStartedAt = `-- name: SetStartedAt :exec
UPDATE user_event_approvals SET started_at = NOW() WHERE id = $1 AND started_at IS NULL
`

func (q *Queries) SetStartedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setStartedAt, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, deleted_at
`

type UpdateCategoryParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.DeletedAt)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2, start_time = $3, end_time = $4, duration_minutes = $5, passing_grade = $6
WHERE id = $1
RETURNING id, name, start_time, end_time, duration_minutes, passing_grade, created_at
`

type UpdateEventParams struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	PassingGrade    string    `json:"passing_grade"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.PassingGrade,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET category_id = $2, question_text = $3, option_a = $4, option_b = $5, option_c = $6, option_d = $7, correct_answer = $8, weight = $9
WHERE id = $1
RETURNING id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at
`

type UpdateQuestionParams struct {
	ID            uuid.UUID     `json:"id"`
	CategoryID    sql.NullInt32 `json:"category_id"`
	QuestionText  string        `json:"question_text"`
	OptionA       string        `json:"option_a"`
	OptionB       string        `json:"option_b"`
	OptionC       string        `json:"option_c"`
	OptionD       string        `json:"option_d"`
	CorrectAnswer string        `json:"correct_answer"`
	Weight        int32         `json:"weight"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion,
		arg.ID,
		arg.CategoryID,
		arg.QuestionText,
		arg.OptionA,
		arg.OptionB,
		arg.OptionC,
		arg.OptionD,
		arg.CorrectAnswer,
		arg.Weight,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, full_name = $3, role = $4, photo_url = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID       uuid.UUID      `json:"id"`
	Username string         `json:"username"`
	FullName string         `json:"full_name"`
	Role     string         `json:"role"`
	PhotoUrl sql.NullString `json:"photo_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.Role,
		arg.PhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPhoto = `-- name: UpdateUserPhoto :exec
UPDATE users SET photo_url = $2 WHERE id = $1
`

type UpdateUserPhotoParams struct {
	ID       uuid.UUID      `json:"id"`
	PhotoUrl sql.NullString `json:"photo_url"`
}

func (q *Queries) UpdateUserPhoto(ctx context.Context, arg UpdateUserPhotoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPhoto, arg.ID, arg.PhotoUrl)
	return err
}
