// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRandomEventQuestionsAll(ctx context.Context, arg AddRandomEventQuestionsAllParams) error
	AddRandomEventQuestionsByCategory(ctx context.Context, arg AddRandomEventQuestionsByCategoryParams) error
	ApproveUserEvent(ctx context.Context, id uuid.UUID) (UserEventApproval, error)
	BlockSession(ctx context.Context, id uuid.UUID) error
	CalculateScore(ctx context.Context, approvalID uuid.NullUUID) (string, error)
	CountAvailableQuestionsForEventAll(ctx context.Context, eventID uuid.UUID) (int64, error)
	CountAvailableQuestionsForEventByCategory(ctx context.Context, arg CountAvailableQuestionsForEventByCategoryParams) (int64, error)
	CountCategories(ctx context.Context, search string) (int64, error)
	CountEventParticipants(ctx context.Context, eventID uuid.NullUUID) (int64, error)
	CountEventQuestions(ctx context.Context, eventID uuid.UUID) (int64, error)
	CountEvents(ctx context.Context, search string) (int64, error)
	CountQuestions(ctx context.Context, search string) (int64, error)
	CountUpcomingEvents(ctx context.Context) (int64, error)
	CountUserApprovals(ctx context.Context, userID uuid.NullUUID) (int64, error)
	CountUsers(ctx context.Context, search string) (int64, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEventQuestion(ctx context.Context, arg CreateEventQuestionParams) error
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteEvent(ctx context.Context, id uuid.UUID) error
	DeleteEventQuestion(ctx context.Context, arg DeleteEventQuestionParams) error
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	EnrollUserToEvent(ctx context.Context, arg EnrollUserToEventParams) (UserEventApproval, error)
	FinishExam(ctx context.Context, arg FinishExamParams) error
	GetAllEventParticipantsForExport(ctx context.Context, eventID uuid.NullUUID) ([]GetAllEventParticipantsForExportRow, error)
	GetApprovalStatus(ctx context.Context, arg GetApprovalStatusParams) (UserEventApproval, error)
	GetCategoryById(ctx context.Context, id int32) (Category, error)
	GetEventById(ctx context.Context, id uuid.UUID) (Event, error)
	GetEventTotalWeight(ctx context.Context, eventID uuid.UUID) (string, error)
	GetQuestionById(ctx context.Context, id uuid.UUID) (Question, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserAnswersDetail(ctx context.Context, approvalID uuid.NullUUID) ([]GetUserAnswersDetailRow, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListEventParticipants(ctx context.Context, arg ListEventParticipantsParams) ([]ListEventParticipantsRow, error)
	ListEventQuestions(ctx context.Context, arg ListEventQuestionsParams) ([]Question, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error)
	ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]Event, error)
	ListUserApprovals(ctx context.Context, arg ListUserApprovalsParams) ([]ListUserApprovalsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SaveUserAnswer(ctx context.Context, arg SaveUserAnswerParams) (UserAnswer, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
