// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const approveUserEvent = `-- name: ApproveUserEvent :one
UPDATE user_event_approvals
SET status = 'approved'
WHERE id = $1
RETURNING id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at
`

func (q *Queries) ApproveUserEvent(ctx context.Context, id uuid.UUID) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, approveUserEvent, id)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const blockSession = `-- name: BlockSession :exec
UPDATE sessions
SET is_blocked = true
WHERE id = $1
`

func (q *Queries) BlockSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, blockSession, id)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, start_time, end_time, duration_minutes, passing_grade)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, start_time, end_time, duration_minutes, passing_grade, created_at
`

type CreateEventParams struct {
	Name            string    `json:"name"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	PassingGrade    string    `json:"passing_grade"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.PassingGrade,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
	)
	return i, err
}

const createEventQuestion = `-- name: CreateEventQuestion :exec
INSERT INTO event_questions (event_id, question_id)
VALUES ($1, $2)
`

type CreateEventQuestionParams struct {
	EventID    uuid.UUID `json:"event_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) CreateEventQuestion(ctx context.Context, arg CreateEventQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createEventQuestion, arg.EventID, arg.QuestionID)
	return err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at
`

type CreateQuestionParams struct {
	CategoryID    sql.NullInt32 `json:"category_id"`
	QuestionText  string        `json:"question_text"`
	OptionA       string        `json:"option_a"`
	OptionB       string        `json:"option_b"`
	OptionC       string        `json:"option_c"`
	OptionD       string        `json:"option_d"`
	CorrectAnswer string        `json:"correct_answer"`
	Weight        int32         `json:"weight"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.CategoryID,
		arg.QuestionText,
		arg.OptionA,
		arg.OptionB,
		arg.OptionC,
		arg.OptionD,
		arg.CorrectAnswer,
		arg.Weight,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, refresh_token, is_blocked, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, full_name, role, photo_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, full_name, role, photo_url, created_at, updated_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	FullName     string         `json:"full_name"`
	Role         string         `json:"role"`
	PhotoUrl     sql.NullString `json:"photo_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.PhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteEventQuestion = `-- name: DeleteEventQuestion :exec
DELETE FROM event_questions
WHERE event_id = $1 AND question_id = $2
`

type DeleteEventQuestionParams struct {
	EventID    uuid.UUID `json:"event_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) DeleteEventQuestion(ctx context.Context, arg DeleteEventQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventQuestion, arg.EventID, arg.QuestionID)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const enrollUserToEvent = `-- name: EnrollUserToEvent :one
INSERT INTO user_event_approvals (user_id, event_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at
`

type EnrollUserToEventParams struct {
	UserID  uuid.NullUUID `json:"user_id"`
	EventID uuid.NullUUID `json:"event_id"`
}

func (q *Queries) EnrollUserToEvent(ctx context.Context, arg EnrollUserToEventParams) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, enrollUserToEvent, arg.UserID, arg.EventID)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT id, name FROM categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategoryById(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryById, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getEventById = `-- name: GetEventById :one
SELECT id, name, start_time, end_time, duration_minutes, passing_grade, created_at FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionById = `-- name: GetQuestionById :one
SELECT id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at FROM questions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQuestionById(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionById, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token, is_blocked, expires_at, created_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name FROM categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventParticipants = `-- name: ListEventParticipants :many
SELECT u.id, u.username, u.full_name, uea.status, uea.is_completed, uea.score, uea.is_passed
FROM users u
JOIN user_event_approvals uea ON u.id = uea.user_id
WHERE uea.event_id = $1
ORDER BY u.full_name ASC
`

type ListEventParticipantsRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	FullName    string         `json:"full_name"`
	Status      string         `json:"status"`
	IsCompleted bool           `json:"is_completed"`
	Score       sql.NullString `json:"score"`
	IsPassed    sql.NullBool   `json:"is_passed"`
}

func (q *Queries) ListEventParticipants(ctx context.Context, eventID uuid.NullUUID) ([]ListEventParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventParticipants, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventParticipantsRow{}
	for rows.Next() {
		var i ListEventParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.IsPassed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventQuestions = `-- name: ListEventQuestions :many
SELECT q.id, q.category_id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.weight, q.created_at FROM questions q
JOIN event_questions eq ON q.id = eq.question_id
WHERE eq.event_id = $1
ORDER BY q.created_at ASC
`

func (q *Queries) ListEventQuestions(ctx context.Context, eventID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listEventQuestions, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.QuestionText,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.CorrectAnswer,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, start_time, end_time, duration_minutes, passing_grade, created_at FROM events
ORDER BY created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.PassingGrade,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at FROM questions
ORDER BY created_at DESC
`

func (q *Queries) ListQuestions(ctx context.Context) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.QuestionText,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.CorrectAnswer,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUserAnswer = `-- name: SaveUserAnswer :one
INSERT INTO user_answers (approval_id, question_id, selected_answer, is_correct)
VALUES ($1, $2, $3, $4)
ON CONFLICT (approval_id, question_id) 
DO UPDATE SET 
    selected_answer = EXCLUDED.selected_answer, 
    is_correct = EXCLUDED.is_correct
RETURNING id, approval_id, question_id, selected_answer, is_correct, created_at
`

type SaveUserAnswerParams struct {
	ApprovalID     uuid.NullUUID  `json:"approval_id"`
	QuestionID     uuid.NullUUID  `json:"question_id"`
	SelectedAnswer sql.NullString `json:"selected_answer"`
	IsCorrect      sql.NullBool   `json:"is_correct"`
}

func (q *Queries) SaveUserAnswer(ctx context.Context, arg SaveUserAnswerParams) (UserAnswer, error) {
	row := q.db.QueryRowContext(ctx, saveUserAnswer,
		arg.ApprovalID,
		arg.QuestionID,
		arg.SelectedAnswer,
		arg.IsCorrect,
	)
	var i UserAnswer
	err := row.Scan(
		&i.ID,
		&i.ApprovalID,
		&i.QuestionID,
		&i.SelectedAnswer,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdateCategoryParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2, start_time = $3, end_time = $4, duration_minutes = $5, passing_grade = $6
WHERE id = $1
RETURNING id, name, start_time, end_time, duration_minutes, passing_grade, created_at
`

type UpdateEventParams struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	PassingGrade    string    `json:"passing_grade"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.PassingGrade,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET category_id = $2, question_text = $3, option_a = $4, option_b = $5, option_c = $6, option_d = $7, correct_answer = $8, weight = $9
WHERE id = $1
RETURNING id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at
`

type UpdateQuestionParams struct {
	ID            uuid.UUID     `json:"id"`
	CategoryID    sql.NullInt32 `json:"category_id"`
	QuestionText  string        `json:"question_text"`
	OptionA       string        `json:"option_a"`
	OptionB       string        `json:"option_b"`
	OptionC       string        `json:"option_c"`
	OptionD       string        `json:"option_d"`
	CorrectAnswer string        `json:"correct_answer"`
	Weight        int32         `json:"weight"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion,
		arg.ID,
		arg.CategoryID,
		arg.QuestionText,
		arg.OptionA,
		arg.OptionB,
		arg.OptionC,
		arg.OptionD,
		arg.CorrectAnswer,
		arg.Weight,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}
