// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Dev Team Pramuka CAT",
            "url": "https://github.com/odealidj/pramuka-CAT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Kategori"
                ],
                "summary": "Daftar Kategori Soal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Category"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Kategori"
                ],
                "summary": "Buat Kategori Soal",
                "parameters": [
                    {
                        "description": "Nama Kategori",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Category"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/categories/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Kategori"
                ],
                "summary": "Update Kategori Soal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Kategori",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nama Baru",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Category"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Kategori"
                ],
                "summary": "Hapus Kategori Soal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Kategori",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/events": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Event"
                ],
                "summary": "Daftar Event Ujian",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Event"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Event"
                ],
                "summary": "Buat Event Ujian",
                "parameters": [
                    {
                        "description": "Data Event",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Event"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/events/{id}/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Download rekap nilai peserta dalam format Excel (.xlsx) atau PDF",
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "Admin - Event"
                ],
                "summary": "Export Laporan Peserta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID Event",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Format file: excel (default) atau pdf",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/questions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Bank Soal"
                ],
                "summary": "Daftar Soal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Question"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Bank Soal"
                ],
                "summary": "Buat Soal Baru",
                "parameters": [
                    {
                        "description": "Data Soal",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.CreateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Question"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/questions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Bank Soal"
                ],
                "summary": "Detail Soal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID Soal",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Question"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Bank Soal"
                ],
                "summary": "Update Soal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID Soal",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Soal Baru",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpdateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Question"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Bank Soal"
                ],
                "summary": "Hapus Soal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID Soal",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil daftar seluruh pengguna dengan paginasi",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - User"
                ],
                "summary": "Daftar Semua User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Halaman (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Jumlah per halaman (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin membuat akun peserta atau admin baru",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - User"
                ],
                "summary": "Buat User Baru",
                "parameters": [
                    {
                        "description": "Data User Baru",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil data detail satu pengguna berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - User"
                ],
                "summary": "Detail User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID User",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin memperbarui data profil pengguna",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - User"
                ],
                "summary": "Update Data User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID User",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data yang diperbarui",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin menonaktifkan akun pengguna (data tidak benar-benar dihapus)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - User"
                ],
                "summary": "Hapus User (Soft-Delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID User",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin mengubah kata sandi pengguna",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - User"
                ],
                "summary": "Update Password User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID User",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Password Baru",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpdateUserPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Autentikasi pengguna dan mendapatkan Access Token \u0026 Refresh Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Kredensial Login",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Memperbarui Access Token menggunakan Refresh Token yang masih berlaku",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Token",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.RefreshResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/protected/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Membatalkan sesi aktif dan menginvalidasi token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/protected/exams/enroll": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Peserta mendaftar ke suatu event ujian (status awal: pending)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Peserta - Ujian"
                ],
                "summary": "Daftar ke Event Ujian",
                "parameters": [
                    {
                        "description": "ID Event",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.EnrollEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/protected/exams/my-exams": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Peserta melihat daftar pendaftaran \u0026 nilai ujian miliknya",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Peserta - Ujian"
                ],
                "summary": "Riwayat Ujian Saya",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UserApproval"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/protected/exams/upcoming": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Peserta melihat event ujian yang belum berakhir",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Peserta - Ujian"
                ],
                "summary": "Daftar Event Mendatang",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpcomingEvent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.CreateCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.CreateEventRequest": {
            "type": "object",
            "required": [
                "duration_minutes",
                "end_time",
                "name",
                "passing_grade",
                "start_time"
            ],
            "properties": {
                "duration_minutes": {
                    "type": "integer",
                    "minimum": 1
                },
                "end_time": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "passing_grade": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.CreateQuestionRequest": {
            "type": "object",
            "required": [
                "correct_answer",
                "option_a",
                "option_b",
                "option_c",
                "option_d",
                "question_text",
                "weight"
            ],
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "correct_answer": {
                    "type": "string",
                    "enum": [
                        "A",
                        "B",
                        "C",
                        "D"
                    ]
                },
                "option_a": {
                    "type": "string"
                },
                "option_b": {
                    "type": "string"
                },
                "option_c": {
                    "type": "string"
                },
                "option_d": {
                    "type": "string"
                },
                "question_text": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.CreateUserRequest": {
            "type": "object",
            "required": [
                "full_name",
                "password",
                "role",
                "username"
            ],
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "photo_url": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "peserta"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.EnrollEventRequest": {
            "type": "object",
            "required": [
                "event_id"
            ],
            "properties": {
                "event_id": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Event": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "passing_grade": {
                    "type": "number"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UserResponse"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.Question": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "correct_answer": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "option_a": {
                    "type": "string"
                },
                "option_b": {
                    "type": "string"
                },
                "option_c": {
                    "type": "string"
                },
                "option_d": {
                    "type": "string"
                },
                "question_text": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.RefreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpcomingEvent": {
            "type": "object",
            "properties": {
                "duration_minutes": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "passing_grade": {
                    "type": "number"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpdateCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpdateQuestionRequest": {
            "type": "object",
            "required": [
                "correct_answer",
                "option_a",
                "option_b",
                "option_c",
                "option_d",
                "question_text",
                "weight"
            ],
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "correct_answer": {
                    "type": "string",
                    "enum": [
                        "A",
                        "B",
                        "C",
                        "D"
                    ]
                },
                "option_a": {
                    "type": "string"
                },
                "option_b": {
                    "type": "string"
                },
                "option_c": {
                    "type": "string"
                },
                "option_d": {
                    "type": "string"
                },
                "question_text": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpdateUserPasswordRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UpdateUserRequest": {
            "type": "object",
            "required": [
                "full_name",
                "role",
                "username"
            ],
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "peserta"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UserApproval": {
            "type": "object",
            "properties": {
                "approval_id": {
                    "type": "string"
                },
                "completed_at": {
                    "type": "string"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "event_id": {
                    "type": "string"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "is_passed": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "passing_grade": {
                    "type": "number"
                },
                "score": {
                    "type": "number"
                },
                "start_time": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "description": "pending, approved, revoked",
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_internal_core_domain.UserResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorDetail": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.ErrorDetail"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Terjadi kesalahan"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_pkg_response.Meta": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_pkg_response.PaginatedResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_odealidj_pramuka-CAT_backend_pkg_response.Meta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_odealidj_pramuka-CAT_backend_pkg_response.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operasi berhasil"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token JWT dengan format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Pramuka CAT API",
	Description:      "REST API untuk platform Computer Assisted Test (CAT) Pramuka.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
